////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2023 Vladislav Trifochkin
//
// This file is part of `debby-lib`.
//
// Changelog:
//      2023.11.25 Initial version.
////////////////////////////////////////////////////////////////////////////////
#include <string>

extern "C" {
#include <libpq-fe.h>
}

namespace debby {
namespace backend {
namespace psql {

inline std::string build_errstr (PGconn * dbh)
{
    if (dbh == nullptr)
        return std::string{};

    // Returns the error message most recently generated by an operation
    // on the connection.
    // Note that by 'libpq' convention, a nonempty 'PQerrorMessage'
    // result can consist of multiple lines, and will include a trailing
    // newline. The caller should not free the result directly.
    // It will be freed when the associated PGconn handle is passed to
    // PQfinish . The result string should not be expected to remain
    // the same across operations on the PGconn structure.
    std::string r(PQerrorMessage(dbh));

    return r;
}

}}} // namespace debby::backend::psql
