////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2021 Vladislav Trifochkin
//
// This file is part of [debby-lib](https://github.com/semenovf/debby-lib) library.
//
// Changelog:
//      2021.12.07 Initial version.
////////////////////////////////////////////////////////////////////////////////
#pragma once
#include "basic_database.hpp"
#include <string>
#include <vector>
#include <cstring>

namespace pfs {
namespace debby {

template <typename Impl, typename Traits>
class keyvalue_database : public basic_database<Impl>
{
    using key_type = typename Traits::key_type;

public:
    /**
     * bool keyvalue_database::set (key_type const & key, T value)
     *
     * Stores @a value by @a key.
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend.
     */
    template <typename T>
    typename std::enable_if<std::is_arithmetic<T>::value, bool>::type
    set (key_type const & key, T value)
    {
        return static_cast<Impl*>(this)->set_impl(key, value);
    }

    /**
     * Stores @a value by @a key.
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend.
     */
    bool set (key_type const & key, std::string const & value)
    {
        return static_cast<Impl*>(this)->set_impl(key, value);
    }

    /**
     * Stores @c char sequence @a value with length @a len by @a key.
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend.
     */
    bool set (key_type const & key, char const * value, std::size_t len)
    {
        return static_cast<Impl*>(this)->set_impl(key, value, len);
    }

    /**
     * Sets C-string @a value by @a key.
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend.
     */
    bool set (key_type const & key, char const * value)
    {
        return static_cast<Impl*>(this)->set_impl(key, value, std::strlen(value));
    }

    /**
     * Fetches value by @a key.
     *
     * @return @c nullopt if @a key not found or contained value on success
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend or unsuitable value stored by @a key
     */
    template <typename T>
    optional<T> get (key_type const & key)
    {
        return static_cast<Impl*>(this)->template get_impl<T>(key);
    }

    /**
     * Removes entry by @a key.
     *
     * @throw debby::runtime_error if error occurred generated by underlying
     *        backend.
     */
    bool remove (key_type const & key)
    {
        return static_cast<Impl*>(this)->remove_impl(key);
    }
};

}} // namespace pfs::debby
