#!/bin/bash

CMAKE_OPTIONS="-DDEBBY__ENABLE_SQLITE3=ON\
 -DDEBBY__ENABLE_LIBMDBX=ON\
 -DDEBBY__ENABLE_ROCKSDB=ON\
 -DDEBBY__ENABLE_MAP=ON\
 -DDEBBY__ENABLE_UNORDERED_MAP=ON\
 -DDEBBY__ENABLE_ROCKSDB=ON"
BUILD_DIR_SUFFIX=.all-backends

. ./build-linux.sh
