#!/bin/bash

CMAKE_OPTIONS="-DDEBBY__ENABLE_SQLITE3=ON -DDEBBY__ENABLE_ROCKSDB=ON -DDEBBY__ENABLE_EXCEPTIONS=1"
PROJECT_OPT_PREFIX=DEBBY__
CXX_STANDARD=11
BUILD_DIR_SUFFIX=.RocksDB.except
BUILD_TESTS=ON
BUILD_DEMO=ON

. ../build.sh
