#!/bin/bash

CMAKE_OPTIONS="-DPFS_DEBBY__ENABLE_SQLITE3=ON -DPFS_DEBBY__ENABLE_ROCKSDB=ON -DPFS_DEBBY__ENABLE_EXCEPTIONS=1"
PROJECT_OPT_PREFIX=PFS_DEBBY__
CXX_STANDARD=11
BUILD_DIR_SUFFIX=.RocksDB.except
BUILD_TESTS=ON
BUILD_DEMO=ON

. ../build.sh
