set CMAKE_OPTIONS=-DDEBBY__ENABLE_SQLITE3=ON -DDEBBY__ENABLE_ROCKSDB=ON
set PROJECT_OPT_PREFIX=DEBBY__
set CXX_STANDARD=11
set BUILD_DIR_SUFFIX=.RocksDB
set BUILD_TESTS=ON
set BUILD_DEMO=ON

call build-windows.cmd
