#!/bin/bash

CMAKE_OPTIONS="-DDEBBY__ENABLE_SQLITE3=ON -DDEBBY__ENABLE_ROCKSDB=ON -DDEBBY__ENABLE_EXCEPTIONS=OFF"
PROJECT_OPT_PREFIX=DEBBY__
CXX_STANDARD=11
BUILD_DIR_SUFFIX=.RocksDB.noexcept
BUILD_TESTS=ON
BUILD_DEMO=ON

. ../build.sh
